### ISSUE TITLE
Error materializing ACL file

### ISSUE THREAD

**Issue by safa-topal** [dragonflydb/dragonfly#2094]
**Describe the bug**
Getting an error as such ` acl_family.cc:234] Error materializing acl file` after issuing `ACL LOAD` command with a known-valid Redis ACL file:

```
user default on #{password_hash} +@all allchannels ~*
user test on #{password_hash} +@all allchannels ~*
```

**To Reproduce**
1. Create an ACL file with the contents shared above.
2. Try to load ACLs via  `ACL LOAD` command or restart the Dragonfly process with the ACL config provided to process.
3. Error on the Dragonfly logs: `(error) ERR Error loading: /path/redis.acl Error materializing acl file`

**Expected behavior**
Redis ACL file should be loaded succesfully with `ACL LOAD` command 

**Environment (please complete the following information):**
 - OS: Fedora 37
 - Kernel: 6.3.12-100.aiven1.fc37.x86_64
 - Containerized?: Fedora toolbox container
 - Dragonfly Version: 1.11.0

**Comment by kostasrim** [comment]
Hi @safa-topal 

Thank you for reporting this. There are two issues:

1. I accidentally used `>` character instead of `#` in the acl file to denote the start of the password. This is straightforward fix which I will submit soon.
2. We do not yet support `pub/sub` and key patterns `~*`. When I implemented the parsing logic of ACL files, I could have ignored those fields and only load the ones we support but I thought that this would be a confusing behaviour because it would imply we have support for something that we don't. 

Therefore, after the `>`/`#` fix, the acl file should look: 

```
user default on #{password_hash} +@all
user test on #{password_hash} +@all
```

For now, you can replace `#` with `>` and remove the unsupported patterns from the file and it should work.

**Comment by safa-topal** [comment]
Hi @kostasrim, thanks for swift response. Good to know there's a possible workaround with the latest release.

> I am also curious, do you need patterns for keys? ~*, etc or pub/sub ACL's ?

Yes, we do. It's a supported feature for Redis and ideally good to have the same support for Dragonfly.

**Comment by romange** [comment]
Hi @safa-topal , as Kostas mentioned our ACL support currently does not cover key and pub/sub use-cases. I agree that this is missing to be on par with Redis, having said that, lets prioritize this feature offline (via slack).

**Comment by safa-topal** [comment]
Hi @kostasrim,

I didn't manage to get the `ACL LOAD` working with the file content below, am I missing some detail? Still getting the same error log.

```
user default on >{password_hash} +@ALL
user test on >{password_hash} +@ALL
```

**Comment by kostasrim** [comment]
Hi @safa-topal ,

try

```
ACL SETUSER default
instead of
USER default
```

again some small compatibility differences -- I will take care of them. Sorry for the inconvenience

**Comment by safa-topal** [comment]
@kostasrim thank you, it worked like a charm.

**Comment by kostasrim** [comment]
@safa-topal Will push the fixes soon :pray:

**Comment by kostasrim** [comment]
Hi @safa-topal, I merged the fixes so I am closing this issue. If you find any other problem, let me know :)

**Comment by safa-topal** [comment]
Does it still make sense to create another issue to track the development for key and pub/sub ACL patterns since this one is closed?
