### ISSUE TITLE
`dragonfly/replication_test.py::test_replication_all` fails sporadically

### ISSUE THREAD

**Issue by chakaz** [dragonflydb/dragonfly#3414]
[Example](https://github.com/dragonflydb/dragonfly/actions/runs/10129412325)

**Comment by kostasrim** [comment]
@chakaz what is this for ? The failure we see is from the flag I introduced

**Comment by kostasrim** [comment]
I think we got confused somewhere. The CI failure you linked, happened on Sunday and the failures that we see are because of `--serialization_max_chunk_size=1` which you reverted the same day. I relater introduced it on Monday with the necessary fixes so what we see above is already resolved no ?

We still got a sporadic failure which triggers an assertion and I am working on it so I am also confused why this was assigned to Vlad

**Comment by chakaz** [comment]
Sorry, I forgot that you are working on this. I'll un-assign Vlad then.

We still see failures here, right? Perhaps I mistakenly linked to one that's related to the serialization that you already fixed.

**Comment by kostasrim** [comment]
yes, there is one corner case in some flow + another flow which I already have a fix but I will push it together with this one

**Comment by kostasrim** [comment]
We also did not handle expirations, flushall, deletions. The PR linked addresses those.
